import { BlockConfig, BlockId, PickaxeTier, BiomeInfo } from '../types/game';

export const GRID_SIZE = 16; // 4x4 inventory grid
export const BASE_MAX_ACTIVE_PICKAXES = 3;
export const BASE_DROP_COOLDOWN = 3.5; // seconds

export const PICKAXE_TIERS: PickaxeTier[] = [
  {
    tier: 1,
    id: 'wooden',
    name: 'Wooden Pickaxe',
    nameRu: 'Деревянная кирка',
    damage: 3,
    hp: 100,
    gravity: 0.065,
    maxSpeedY: 2.8,
    color: '#8A5826',
    bladeColor: '#A47148',
    handleColor: '#6B4423',
    cost: 15,
    specialEffectRu: 'Лёгкая начальная кирка',
  },
  {
    tier: 2,
    id: 'stone',
    name: 'Stone Pickaxe',
    nameRu: 'Каменная кирка',
    damage: 8,
    hp: 260,
    gravity: 0.075,
    maxSpeedY: 3.2,
    color: '#7D7D7D',
    bladeColor: '#9E9E9E',
    handleColor: '#6B4423',
    cost: 40,
    specialEffectRu: 'Прочный камень (+HP)',
  },
  {
    tier: 3,
    id: 'iron',
    name: 'Iron Pickaxe',
    nameRu: 'Железная кирка',
    damage: 22,
    hp: 700,
    gravity: 0.088,
    maxSpeedY: 3.8,
    color: '#E0E0E0',
    bladeColor: '#FFFFFF',
    handleColor: '#6B4423',
    cost: 130,
    specialEffectRu: 'Стальной удар',
  },
  {
    tier: 4,
    id: 'golden',
    name: 'Golden Pickaxe',
    nameRu: 'Золотая кирка',
    damage: 60,
    hp: 1600,
    gravity: 0.100,
    maxSpeedY: 4.4,
    color: '#FDCB02',
    bladeColor: '#FFF275',
    handleColor: '#6B4423',
    cost: 420,
    glowColor: '#FFD700',
    specialEffectRu: 'Золотая лихорадка (+25% монет)',
  },
  {
    tier: 5,
    id: 'diamond',
    name: 'Diamond Pickaxe',
    nameRu: 'Алмазная кирка',
    damage: 160,
    hp: 4000,
    gravity: 0.115,
    maxSpeedY: 5.0,
    color: '#2DD4BF',
    bladeColor: '#5EEAD4',
    handleColor: '#6B4423',
    cost: 1400,
    glowColor: '#2DD4BF',
    specialEffectRu: 'Алмазная резка пород',
  },
  {
    tier: 6,
    id: 'netherite',
    name: 'Netherite Pickaxe',
    nameRu: 'Незеритовая кирка',
    damage: 460,
    hp: 11000,
    gravity: 0.130,
    maxSpeedY: 5.6,
    color: '#3B3338',
    bladeColor: '#524850',
    handleColor: '#262024',
    cost: 4600,
    glowColor: '#7E6B77',
    specialEffectRu: 'Взрывная волна по соседям',
  },
  {
    tier: 7,
    id: 'amethyst',
    name: 'Amethyst Pickaxe',
    nameRu: 'Аметистовая кирка',
    damage: 1300,
    hp: 30000,
    gravity: 0.145,
    maxSpeedY: 6.2,
    color: '#A855F7',
    bladeColor: '#C084FC',
    handleColor: '#581C87',
    cost: 15000,
    glowColor: '#A855F7',
    specialEffectRu: 'Осколочные кристаллы',
  },
  {
    tier: 8,
    id: 'emerald',
    name: 'Emerald Pickaxe',
    nameRu: 'Изумрудная кирка',
    damage: 3800,
    hp: 85000,
    gravity: 0.160,
    maxSpeedY: 6.8,
    color: '#22C55E',
    bladeColor: '#4ADE80',
    handleColor: '#14532D',
    cost: 50000,
    glowColor: '#22C55E',
    specialEffectRu: 'Двойные изумруды',
  },
  {
    tier: 9,
    id: 'redstone',
    name: 'Redstone Core Pickaxe',
    nameRu: 'Редстоун-кирка',
    damage: 11000,
    hp: 250000,
    gravity: 0.175,
    maxSpeedY: 7.4,
    color: '#EF4444',
    bladeColor: '#F87171',
    handleColor: '#7F1D1D',
    cost: 180000,
    glowColor: '#EF4444',
    specialEffectRu: 'Электро-разряд по цепи блоков',
  },
  {
    tier: 10,
    id: 'obsidian',
    name: 'Obsidian Cleaver',
    nameRu: 'Обсидиановая кирка',
    damage: 34000,
    hp: 750000,
    gravity: 0.190,
    maxSpeedY: 8.0,
    color: '#1E1035',
    bladeColor: '#3B1D6B',
    handleColor: '#0E071A',
    cost: 600000,
    glowColor: '#9333EA',
    specialEffectRu: 'Сокрушение самых твердых пород',
  },
  {
    tier: 11,
    id: 'sculk',
    name: 'Sculk Reaper',
    nameRu: 'Скалковая кирка',
    damage: 110000,
    hp: 2200000,
    gravity: 0.210,
    maxSpeedY: 8.8,
    color: '#083344',
    bladeColor: '#0E7490',
    handleColor: '#021B24',
    cost: 2000000,
    glowColor: '#06B6D4',
    specialEffectRu: 'Акустический сокрушитель',
  },
  {
    tier: 12,
    id: 'ender',
    name: 'Cosmic Ender Pickaxe',
    nameRu: 'Кирка Края',
    damage: 380000,
    hp: 7000000,
    gravity: 0.230,
    maxSpeedY: 9.6,
    color: '#701A75',
    bladeColor: '#C026D3',
    handleColor: '#4A044E',
    cost: 7000000,
    glowColor: '#E879F9',
    specialEffectRu: 'Разрыв пространства и пустоты',
  },
];

export const BLOCK_CONFIGS: Record<BlockId, BlockConfig> = {
  // Surface blocks (Row 0 only)
  grass: {
    id: 'grass',
    name: 'Grass',
    nameRu: 'Дёрн',
    baseHp: 12,
    coinReward: 2,
    emeraldReward: 0,
    color: '#5B8731',
    particleColor: '#5B8731',
  },
  dirt: {
    id: 'dirt',
    name: 'Dirt',
    nameRu: 'Земля',
    baseHp: 16,
    coinReward: 2,
    emeraldReward: 0,
    color: '#866043',
    particleColor: '#866043',
  },

  // Early Sediments & Soft Stone
  wood: {
    id: 'wood',
    name: 'Oak Wood',
    nameRu: 'Дуб',
    baseHp: 35,
    coinReward: 4,
    emeraldReward: 0,
    color: '#9C7A4A',
    particleColor: '#9C7A4A',
  },
  gravel: {
    id: 'gravel',
    name: 'Gravel',
    nameRu: 'Гравий',
    baseHp: 45,
    coinReward: 5,
    emeraldReward: 0,
    color: '#828282',
    particleColor: '#9E9E9E',
  },
  sandstone: {
    id: 'sandstone',
    name: 'Sandstone',
    nameRu: 'Песчаник',
    baseHp: 55,
    coinReward: 7,
    emeraldReward: 0,
    color: '#D8C58D',
    particleColor: '#D8C58D',
  },

  // Stone Layer & Natural Minerals (Diorite replaces Dirt!)
  diorite: {
    id: 'diorite',
    name: 'Diorite',
    nameRu: 'Диорит',
    baseHp: 80,
    coinReward: 10,
    emeraldReward: 0,
    color: '#BDBDBD',
    particleColor: '#FFFFFF',
  },
  andesite: {
    id: 'andesite',
    name: 'Andesite',
    nameRu: 'Андезит',
    baseHp: 110,
    coinReward: 14,
    emeraldReward: 0,
    color: '#888888',
    particleColor: '#888888',
  },
  granite: {
    id: 'granite',
    name: 'Granite',
    nameRu: 'Гранит',
    baseHp: 140,
    coinReward: 18,
    emeraldReward: 0,
    color: '#9A6B59',
    particleColor: '#B07B67',
  },
  stone: {
    id: 'stone',
    name: 'Stone',
    nameRu: 'Камень',
    baseHp: 180,
    coinReward: 24,
    emeraldReward: 0,
    color: '#767676',
    particleColor: '#767676',
  },
  coal_ore: {
    id: 'coal_ore',
    name: 'Coal Ore',
    nameRu: 'Угольная руда',
    baseHp: 260,
    coinReward: 40,
    emeraldReward: 0,
    color: '#555555',
    particleColor: '#2B2B2B',
  },
  copper_ore: {
    id: 'copper_ore',
    name: 'Copper Ore',
    nameRu: 'Медная руда',
    baseHp: 440,
    coinReward: 75,
    emeraldReward: 0,
    color: '#656565',
    particleColor: '#D97706',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    nameRu: 'Железная руда',
    baseHp: 850,
    coinReward: 160,
    emeraldReward: 0,
    color: '#6E6E6E',
    particleColor: '#D1B499',
  },

  // Deepslate Strata (Твёрдый сланец replaces Stone!)
  tuff: {
    id: 'tuff',
    name: 'Tuff',
    nameRu: 'Туф',
    baseHp: 1500,
    coinReward: 320,
    emeraldReward: 0,
    color: '#4F5448',
    particleColor: '#5C6254',
  },
  deepslate: {
    id: 'deepslate',
    name: 'Deepslate',
    nameRu: 'Твёрдый сланец',
    baseHp: 2400,
    coinReward: 520,
    emeraldReward: 0,
    color: '#34343B',
    particleColor: '#34343B',
  },
  gold_ore: {
    id: 'gold_ore',
    name: 'Gold Ore',
    nameRu: 'Золотая руда',
    baseHp: 4800,
    coinReward: 950,
    emeraldReward: 1,
    color: '#6E6E6E',
    particleColor: '#FBBF24',
  },
  lapis_ore: {
    id: 'lapis_ore',
    name: 'Lapis Ore',
    nameRu: 'Лазуритовая руда',
    baseHp: 9500,
    coinReward: 2000,
    emeraldReward: 2,
    color: '#666666',
    particleColor: '#2563EB',
  },
  redstone_ore: {
    id: 'redstone_ore',
    name: 'Redstone Ore',
    nameRu: 'Редстоун руда',
    baseHp: 22000,
    coinReward: 4500,
    emeraldReward: 3,
    color: '#5E5E5E',
    particleColor: '#DC2626',
  },

  // Crystal & Diamond Layer
  diamond_ore: {
    id: 'diamond_ore',
    name: 'Diamond Ore',
    nameRu: 'Алмазная руда',
    baseHp: 55000,
    coinReward: 12000,
    emeraldReward: 8,
    color: '#5E5E5E',
    particleColor: '#2DD4BF',
  },
  emerald_ore: {
    id: 'emerald_ore',
    name: 'Emerald Ore',
    nameRu: 'Изумрудная руда',
    baseHp: 130000,
    coinReward: 30000,
    emeraldReward: 20,
    color: '#5E5E5E',
    particleColor: '#10B981',
  },
  amethyst_block: {
    id: 'amethyst_block',
    name: 'Amethyst Block',
    nameRu: 'Блок аметиста',
    baseHp: 280000,
    coinReward: 70000,
    emeraldReward: 35,
    color: '#8B5CF6',
    particleColor: '#C084FC',
  },

  // Nether Layer
  netherrack: {
    id: 'netherrack',
    name: 'Netherrack',
    nameRu: 'Незерак',
    baseHp: 520000,
    coinReward: 120000,
    emeraldReward: 40,
    color: '#682020',
    particleColor: '#852828',
  },
  soul_sand: {
    id: 'soul_sand',
    name: 'Soul Sand',
    nameRu: 'Песок душ',
    baseHp: 900000,
    coinReward: 200000,
    emeraldReward: 55,
    color: '#513E32',
    particleColor: '#6B5242',
  },
  basalt: {
    id: 'basalt',
    name: 'Basalt',
    nameRu: 'Базальт',
    baseHp: 1600000,
    coinReward: 350000,
    emeraldReward: 70,
    color: '#4F4F54',
    particleColor: '#36363B',
  },
  blackstone: {
    id: 'blackstone',
    name: 'Blackstone',
    nameRu: 'Чернит',
    baseHp: 3000000,
    coinReward: 600000,
    emeraldReward: 90,
    color: '#272228',
    particleColor: '#3B353D',
  },
  crying_obsidian: {
    id: 'crying_obsidian',
    name: 'Crying Obsidian',
    nameRu: 'Плачущий обсидиан',
    baseHp: 6500000,
    coinReward: 1300000,
    emeraldReward: 140,
    color: '#281140',
    particleColor: '#A855F7',
  },
  ancient_debris: {
    id: 'ancient_debris',
    name: 'Ancient Debris',
    nameRu: 'Древние обломки',
    baseHp: 14000000,
    coinReward: 3000000,
    emeraldReward: 220,
    color: '#49372F',
    particleColor: '#785A48',
  },
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian',
    nameRu: 'Обсидиан',
    baseHp: 30000000,
    coinReward: 7000000,
    emeraldReward: 350,
    color: '#160E24',
    particleColor: '#4A1D75',
  },

  // The End Void Realm
  end_stone: {
    id: 'end_stone',
    name: 'End Stone',
    nameRu: 'Камень Края',
    baseHp: 75000000,
    coinReward: 18000000,
    emeraldReward: 600,
    color: '#DCDE9F',
    particleColor: '#E6E8B5',
  },
  purpur: {
    id: 'purpur',
    name: 'Purpur Block',
    nameRu: 'Блок пурпура',
    baseHp: 180000000,
    coinReward: 45000000,
    emeraldReward: 1200,
    color: '#A97CA9',
    particleColor: '#C494C4',
  },

  // Specials
  tnt: {
    id: 'tnt',
    name: 'TNT',
    nameRu: 'Динамит',
    baseHp: 15,
    coinReward: 50,
    emeraldReward: 2,
    color: '#DB2727',
    particleColor: '#EF4444',
    isSpecial: true,
  },
  chest: {
    id: 'chest',
    name: 'Treasure Chest',
    nameRu: 'Сундук с добычей',
    baseHp: 180,
    coinReward: 350,
    emeraldReward: 15,
    color: '#B45309',
    particleColor: '#F59E0B',
    isSpecial: true,
  },
  bedrock_boss: {
    id: 'bedrock_boss',
    name: 'Bedrock Core',
    nameRu: 'Ядро Биома',
    baseHp: 500000,
    coinReward: 150000,
    emeraldReward: 300,
    color: '#262626',
    particleColor: '#525252',
    isSpecial: true,
  },
};

export const BIOMES: BiomeInfo[] = [
  {
    depthStart: 0,
    depthEnd: 45,
    name: 'Surface & Sediments',
    nameRu: 'Верхний мир и Осадки',
    bgColor: '#1c1b18',
    wallColor: '#2b261f',
    descriptionRu: 'Первый слой травы, земля, песчаник, гравий и диорит',
    allowedBlocks: ['dirt', 'sandstone', 'gravel', 'wood', 'diorite', 'andesite', 'stone', 'tnt', 'chest'],
  },
  {
    depthStart: 45,
    depthEnd: 120,
    name: 'Stone Caverns',
    nameRu: 'Каменные глубины',
    bgColor: '#171717',
    wallColor: '#262626',
    descriptionRu: 'Диорит, андезит, гранит, медь и залежи угля',
    allowedBlocks: ['diorite', 'andesite', 'granite', 'stone', 'coal_ore', 'copper_ore', 'iron_ore', 'tnt', 'chest'],
  },
  {
    depthStart: 120,
    depthEnd: 240,
    name: 'Deepslate Strata',
    nameRu: 'Твёрдый сланец',
    bgColor: '#121214',
    wallColor: '#1d1d21',
    descriptionRu: 'Твёрдый сланец, туф, золото, лазурит и редстоун',
    allowedBlocks: ['deepslate', 'tuff', 'iron_ore', 'gold_ore', 'lapis_ore', 'redstone_ore', 'tnt', 'chest'],
  },
  {
    depthStart: 240,
    depthEnd: 420,
    name: 'Diamond & Crystal Depths',
    nameRu: 'Алмазно-Кристальная бездна',
    bgColor: '#0c1017',
    wallColor: '#141d2b',
    descriptionRu: 'Сияющие кристаллы аметиста, алмазы и изумруды',
    allowedBlocks: ['deepslate', 'gold_ore', 'redstone_ore', 'diamond_ore', 'emerald_ore', 'amethyst_block', 'tnt', 'chest'],
  },
  {
    depthStart: 420,
    depthEnd: 700,
    name: 'Nether Magma Core',
    nameRu: 'Лавовые недра Незера',
    bgColor: '#180a0a',
    wallColor: '#2e1111',
    descriptionRu: 'Незерак, песок душ, базальт, чернит, обломки и плачущий обсидиан',
    allowedBlocks: ['netherrack', 'soul_sand', 'basalt', 'blackstone', 'crying_obsidian', 'ancient_debris', 'obsidian', 'tnt', 'chest'],
  },
  {
    depthStart: 700,
    depthEnd: 999999,
    name: 'Ender Void Realm',
    nameRu: 'Пустота Края',
    bgColor: '#0f0514',
    wallColor: '#230b2e',
    descriptionRu: 'Камень Края, блоки пурпура и несокрушимый обсидиан',
    allowedBlocks: ['crying_obsidian', 'ancient_debris', 'obsidian', 'end_stone', 'purpur', 'bedrock_boss', 'tnt', 'chest'],
  },
];
